# Generated by Django 4.1.3 on 2022-11-28 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mundial", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("bandera", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="jugador",
            name="equipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mundial.equipo"
            ),
        ),
    ]
