# Generated by Django 4.1.3 on 2022-11-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_author_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookinstance",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
    ]
